spring:
  datasource:
    url: jdbc:postgresql://${db.server.host}:${db.server.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: daggerok.domain.json.JsonPostgresDialect
